version: '2'

services:

  application:
    image: tianon/true
    volumes:
      - ../:/var/www

  lp_workspace:
    build:
      context: ./workspace
      args:
        - PUID=1000
        - PGID=1000
        - TZ=UTC
    volumes_from:
      - application
    tty: true

  lp_php-fpm:
    build:
      context: ./php-fpm
    volumes_from:
      - application
    expose:
      - "9000"
    links:
      - lp_workspace

  lp_nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=lp_php-fpm
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    links:
      - lp_php-fpm

  lp_db:
    build:
      context: ./postgres
    environment:
      - POSTGRES_DB=laravel-passport
      - POSTGRES_USER=laravel-passport
      - POSTGRES_PASSWORD=laravel-passport
    volumes:
      - lp_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  lp_db:
    driver: "local"
